//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NearCollegeFINAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Fichos
    {
        public int IdFicho { get; set; }
        public System.DateTime FechaFicho { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Tbl_Usuarios Tbl_Usuarios { get; set; }
    }
}
